const ActionTypes = {
  ADD_MOVIE: 'ADD_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  EDIT_MOVIE: 'EDIT_MOVIE',
  GET_MOVIES: 'GET_MOVIES',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
};

export default ActionTypes;
